# # MoveIt-specific simulation settings
# moveit_sim_hw_interface:
#   joint_model_group: controllers_initial_group_
#   joint_model_group_pose: controllers_initial_pose_
# # Settings for ros_control control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - ur5e_shoulder_pan_joint
#     - ur5e_shoulder_lift_joint
#     - ur5e_elbow_joint
#     - ur5e_wrist_1_joint
#     - ur5e_wrist_2_joint
#     - ur5e_wrist_3_joint
#     - robotiq_palm_finger_1_joint
#     - robotiq_finger_1_joint_1
#     - robotiq_palm_finger_2_joint
#     - robotiq_finger_2_joint_1
#     - robotiq_finger_middle_joint_1

#   sim_control_mode: 1 # 0: position, 1: velocity
# # Publish all joint states
# # Creates the /joint_states topic necessary in ROS
ur5e:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    public_topic: "/ur5e/joint_states"
ur5e_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - ur5e_shoulder_pan_joint
    - ur5e_shoulder_lift_joint
    - ur5e_elbow_joint
    - ur5e_wrist_1_joint
    - ur5e_wrist_2_joint
    - ur5e_wrist_3_joint
  gains:
    ur5e_shoulder_pan_joint:
      p: 4000
      d: 200
      i: 1
      i_clamp: 1
    ur5e_shoulder_lift_joint:
      p: 10000
      d: 200
      i: 1
      i_clamp: 1
    ur5e_elbow_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    ur5e_wrist_1_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_2_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    ur5e_wrist_3_joint:
      p: 100
      d: 10
      i: 1
      i_clamp: 1
  constraints:
    goal_time: 2.0
  state_publish_rate: 25
robotiq_gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - robotiq_palm_finger_1_joint
    - robotiq_finger_1_joint_1
    - robotiq_finger_1_joint_2
    - robotiq_finger_1_joint_3
    - robotiq_palm_finger_2_joint
    - robotiq_finger_2_joint_1
    - robotiq_finger_2_joint_2
    - robotiq_finger_2_joint_3
    - robotiq_finger_middle_joint_1
    - robotiq_finger_middle_joint_2
    - robotiq_finger_middle_joint_3
  gains:
    robotiq_palm_finger_1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_1_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_1_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_1_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_palm_finger_2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_2_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_2_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_2_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_middle_joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_middle_joint_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    robotiq_finger_middle_joint_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
  state_publish_rate: 25

controller_list:
  - name: ur5e_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - ur5e_shoulder_pan_joint
      - ur5e_shoulder_lift_joint
      - ur5e_elbow_joint
      - ur5e_wrist_1_joint
      - ur5e_wrist_2_joint
      - ur5e_wrist_3_joint
  - name: robotiq_gripper_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - robotiq_palm_finger_1_joint
      - robotiq_finger_1_joint_1
      - robotiq_finger_1_joint_2
      - robotiq_finger_1_joint_3
      - robotiq_palm_finger_2_joint
      - robotiq_finger_2_joint_1
      - robotiq_finger_2_joint_2
      - robotiq_finger_2_joint_3
      - robotiq_finger_middle_joint_1
      - robotiq_finger_middle_joint_2
      - robotiq_finger_middle_joint_3
initial: # Define initial robot poses per group
  - group: ur5e_arm
    pose: default_arm_pose
  - group: robotiq_gripper
    pose: Default_pose
